name: Scans

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    # - name: Run Snyk to check for vulnerabilities
    #   uses: snyk/actions/node@master
    #   continue-on-error: true
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
